Routes
CWells1225/backend_ecommerce_hair pull request #6
Opened 2023-10-04 00:42 UTC by CWells1225

Created the controllers and routes. Testing routes

2023-10-06 02:19 UTC, mnebot86 requested changes

2023-10-06 02:19 UTC, mnebot86 commented on controllers/user.js
> +    const userAlreadyExists = await User.findOne({ email: req.body.email });
u already deconstructed email from req.body on line 13. So you can just do   `await User.findOne({ email });`

2023-10-06 02:19 UTC, mnebot86 commented on controllers/user.js
> +    const schema = registerSchema(req.body)
Where is registerSchema coming from?

2023-10-06 02:19 UTC, mnebot86 commented on controllers/user.js
> +        password,
Your saving the password directly to the database. You never want to do this. The password should be hash and salted before storing. Look into the bcrypt library.

2023-10-06 02:19 UTC, mnebot86 commented on controllers/user.js
> +    const token = user.createJWT();
`createJWT` was never created on the User model so this wont work.

2023-10-06 02:19 UTC, mnebot86 commented on controllers/user.js
> +    const isPasswordCoreect = await user.comparePassword(password);
`comparePassword` wasn't created on the User model, so this wont work.

2023-10-06 02:19 UTC, mnebot86 commented on controllers/user.js
> +    const token = user.createJWT();
createJWT was never created on the User model so this wont work.

2023-10-06 02:19 UTC, mnebot86 commented on controllers/user.js
> +    user.password=undefined;
`user.password = undefined;`

2023-10-06 02:19 UTC, mnebot86 commented on controllers/user.js
> +};
add new line

2023-10-06 02:19 UTC, mnebot86 commented on routes/user.js
> +	    login,
fix alignment

2023-10-06 02:19 UTC, mnebot86 commented on routes/user.js
> +    router.get(checkAuth, getUser);
`checkAuth` function doesn't exist

2023-10-18 03:39 UTC, CWells1225 commented
I've updated the user controllers and routes. I started with the sign up controller / route .

2023-11-05 21:52 UTC, merged